import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";

import { api } from "~/utils/api";

const CreatePostForm = () => {

  const { user } = useUser()

  if (!user) return <div>Please log in...</div>

  return (
    <div className="flex">
      <img 
        src={user.imageUrl} 
        alt='profile image' 
        className="h-16 w-16 rounded-full" 
      />
    </div>
  )
};

export default function Home() {
  const user = useUser()
  const { data, isLoading } =  api.posts.getAll.useQuery()

  if (isLoading) return <div>Loading...</div>
  if (!data) return <div>Something went wrong</div>

  return (
    <>
      <Head>
        <title>moji</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className='h-full w-full border-x border-slate-400 md:max-w-2xl'>
          <div className="flex flex-col justify-center p-4 bg-zinc-100 border-b">
            {
              <div className='flex py-4 justify-end'>  
                {!!user.isSignedIn ? <SignOutButton /> : <SignInButton /> }
              </div>
            }
              {user.isSignedIn && <CreatePostForm />}
            </div>
              <div>
              </div>
            <div className="flex flex-col">
              {data.map(post => <div className="p-8 border-b border-slate-400" key={post.id}>{post.content}</div>)}
          </div>
        </div>
      </main>
    </>
  );
};
